version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo

  docker-executor:
    docker:
      - image: docker:20.10.16
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    working_directory: ~/repo

jobs:
  run-lints:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install -y make
      - run:
          name: Run Linting
          command: make lint

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install -y make
      - run:
          name: Run Tests
          command: make test

  build-image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Push Docker Image
          command: docker push $IMAGE_NAME:$IMAGE_TAG
      - run:
          name: Run Docker Image Locally
          command: docker run -it -d -p 3001:3000 $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - run-lints
      - run-tests:
          requires:
            - run-lints
      - build-image:
          requires:
            - run-tests
